var tooltips={
		Statewide_Summary_Report: {
            "State": "Name of the state",
			"Land Area(in sq. mi.)": "Total land area of the state",
			"Total Population": "Total population of the state",
			"Urban Population": "Total population of the state living in urbanized areas",
			"Rural Population": "Total population of the state living in non-urban areas",
			"Transit Agencies Count": "Count of transit agencies operating within the state",
			"Routes Count": "Count of routes within the state",
			"Stops Count": "Count of stops within the state",
			"Urbanized Areas Count": "Count of urbanized areas within the state",
			"Congressional Districts Count": "Count of congressional districts within the state",
			"ODOT Transit Regions Count": "Count of ODOT transit regions within the state",
			"Census Places Count": "Count of census designated places within the state",
			"Counties Count": "Count of counties within the state",
			"Census Tracts Count": "Count of census tracts within the state",			
        },
		"Statewide Extended Report": {
			"State": "Name of the state",
			"Fare": "The fare information published in the transit agency's GTFS feed",
			"Route Miles": "Summation of the lengths of the longest trips within the geographic area",			
			"Service Hours": "This is the total hours a transit agency spends on serving all round trips within the given geographic area. Service Hours may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",			
			"Service Miles": "This is the total miles driven over all round trips within the given geographic area. Service Miles may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Miles Per Square Mile": "Service Miles divided by the area of the given geographic area",
			"Stops Per Square Mile": "Stops Count divided by the area of given geographic area",
			"Stops Per Service Mile": "Stops Count in the given geographic area divided by Service Miles",
			"Miles of Service Per Capita": "Service Miles divided by the population of the geographic area",
			"Population Served (Unduplicated)": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area",
			"Percent of Population Served": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area divided by the total population of the given geographic area",
			"Percent of Population Served at Level of Service": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area that receives a specified minimum level of service divided by total population of the given geographic area",
			"Percent Population Unserved": "One hundred percent minus Percent of Population Served",
			"Service Stops": "This is Stops Count within the given geographic area multiplied by the number of times each stop is being served for the given date(s). The reported numbers are cumulative over the selected dates.",
			"Population Served By Service": "Population Served by Service is calculated as Service Stops multiplied by the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area for every trip. The reported numbers are cumulative over the selected dates.",
			"Service Days": "Set of days (from the selected days) in which at least one trip within the given geographic area is served",
			"Hours of Service": "Earliest arrival and latest departure times of all stops within the given geographic area",
			"Average Fare": "Fare average for the given geographic area",
			"Median Fare": "Fare median for the given geographic area",
			"Min. Fare": "Minimum fare for the state",
			"Max. Fare": "Maximum fare for the state",
			"Urban Area Served (sq.mi.)": "Total area of all urban census blocks served, in square miles",
			"Rural Area Served (sq.mi.)": "Total area of all rural census blocks served, in square miles",
			"Population Density of Urban Area Served (people/sq.mi.)": "The total population of all urban census blocks served divided by the area of the census blocks, in persons per square mile.",
			"Population Density of Rural Area Served (people/sq.mi.)": "The total population of all rural census blocks served divided by the area of the census blocks, in persons per square mile.",
		},
		"Transit Agency Summary Report": {
			"Agency ID": "Identification number reported in the transit agency's GTFS feed",
			"Agency Name": "Agency name reported in the transit agency's GTFS feed",
			"Phone #": "Transit Agency contact phone number",
			"Total Routes": "Total number of routes operated by the transit agency",
			"Total Stops": "Total number of stops operated by the transit agency",
			"Fare": "The fare information published on the transit agency's web site",
		},
		"Transit Agency Extended Report": {
			"Agency ID": "Identification number reported in the transit agency's GTFS feed",
			"Agency Name": "Agency name reported in the transit agency's GTFS feed",
			"Route Miles" : "Summation of the lengths of the longest route variant for all routes that the transit agency serves",
			"Route Stops": "Total number of stops served by the transit agency",
			"Stops Per Route Mile": "Route Stops divided by Route Miles",
			"Population(2010) Served By Agency (Unduplicated)": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops that the transit agency serves",
			"Service Miles": "This is the total miles driven by a transit agency over all round trips of a route. Service Miles may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Hours": "This is the total hours a transit agency spends on serving all round trip routes. Service Hours may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Stops": "This is the number of trips scheduled at a stop in a route. Service Stops for a route is calculated as its stop count multiplied by the number of visits per stop. The reported numbers are cumulative over the selected dates.",
			"Population(2010) Served By Service": "Total unduplicated population impacted within an X-mile radius (i.e., stop distance) of all stops on trips served by the transit agency. Population Served by Service is calculated as Service Stops multiplied by the unduplicated population within an X-mile radius (i.e., stop distance) of all stops for every trip. The reported numbers are cumulative over the selected dates.",
			"Hours of Service": "Earliest arrival and latest departure times of all stops served by the transit agency",
		},
		"Transit Agency Routes Report": {
			"Route ID": "Unique route identification number reported in the transit agency's GTFS feed",
			"Route Name": "Route short name as reported in the transit agency's GTFS feed",
			"Route Long Name": "Route long name as reported in the transit agency's GTFS feed",
			"Route Type": "Type of transportation used on a route: 0-Tram, Streetcar, & Light rail, 1-Subway & Metro, 2-Rail, 3-Bus, 4-Ferry, 5-Cable car, 6-Gondola & Suspended cable car, 7-Funicular",
			"Route Length": "Length of the longest route variant for the given route",
			"Total Stops": "Total number of stops on the route",
			"Unduplicated Population (2010)": "This is the summation of the unduplicated population count within an X radius (i.e., stop distance) of each stop on a route. The default value for X is 0.1 miles. However, the value of the radius can be changed by the user in the text box shown in the upper right corner of the report and then pressing the <Submit> button.",
			"Service Stops": "This is the number of stops scheduled on all trips in a route. Service Stops for a route is calculated as the stop count multiplied by the number of visits per stop.",
			"Population (2010) Served by Route": "This is the total unduplicated population impacted within an X-mile radius (i.e., stop distance) of all stops on all trips. The Population Served by Route for a route is calculated as route service stops multiplied by the unduplicated population within an X-mile radius (i.e., stop distance) of all stops on all trips.",
			"Service Miles": "This is the total miles driven by a transit agency over all round trips of a route. Service Miles may be calculated for a specific date or a set of specified dates using the calendar.",
			"Service Hours": "This is the total hours a transit agency spends on serving all round trips of a route. Service Hours may be calculated for a specific date or a set of specified dates using the calendar.",
			"More..": "If available, this field contains a description of the route (the value is null otherwise).",
		},
		"Transit Agency Schedule Report": {
			
		},
		"Transit Agency Stops Report": {
			"Stop ID": "Unique stop identification number reported in the transit agency's GTFS feed",
			"Stop Name": "Name of a stop reported in the transit agency's GTFS feed",
			"Routes Stop Belongs To": "Unique route ID (or IDs) to which the stop belongs",
			"Population (2010)": "This is the unduplicated population count within an X-mile radius (i.e., stop distance) of a stop. The default value for X is 0.1 miles. However, the value of the radius can be changed by the user in the text box shown in the upper right corner of the report and then pressing the <Submit> button.",
		},
		"Aggregated Urban Areas Summary Report": {
			"Geo ID": "Identification number associated with the geographic area",
			"Name": "Name of the geographic area",
			"Population (2010)": "Total population of the geographic area",
			"Land Area (in sq. mi.)": "Total land area of the geographic area",
			"Water Area (in sq. mi.)": "Total water area of the geographic area",
			"Urban Areas": "Total number of urbanized areas aggregated",
			"Routes Count": "Count of routes within the given geographic area",
			"Stops Count": "Count of stops within the given geographic area",
		},
		"Aggregated Urban Areas Extended Report": {
			"Geo ID": "Identification number associated with the geographic area",
			"Name": "Name of the geographic area",
			"Fare": "The fare information published in the transit agency's GTFS feed",		
			"Route Miles": "Summation of the lengths of the longest trips within the geographic area",			
			"Service Hours": "This is the total hours a transit agency spends on serving all round trips within the given geographic area. Service Hours may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",			
			"Service Miles": "This is the total miles driven over all round trips within the given geographic area. Service Miles may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Miles Per Square Mile": "Service Miles divided by the area of the given geographic area",
			"Stops Per Square Mile": "Stops Count divided by the area of given geographic area",
			"Stops Per Service Mile": "Stops Count in the given geographic area divided by Service Miles",
			"Miles of Service Per Capita": "Service Miles divided by the population of the geographic area",
			"Population Served (Unduplicated)": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area",
			"Percent of Population Served": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area divided by the total population of the given geographic area",
			"Percent of Population Served at Level of Service": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area that receives a specified minimum level of service divided by total population of the given geographic area",
			"Percent Population Unserved": "One hundred percent minus Percent of Population Served",
			"Service Stops": "This is Stops Count within the given geographic area multiplied by the number of times each stop is being served for the given date(s). The reported numbers are cumulative over the selected dates.",
			"Population Served By Service": "Population Served by Service is calculated as Service Stops multiplied by the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area for every trip. The reported numbers are cumulative over the selected dates.",
			"Service Days": "Set of days (from the selected days) in which at least one trip within the given geographic area is served",
			"Connected Communities": "List of geographic areas of the same type that are connected to the given geographic area through routes",
			"Hours of Service": "Earliest arrival and latest departure times of all stops within the given geographic area",
			"Average Fare": "Fare average for the given geographic area",
			"Median Fare": "Fare median for the given geographic area",			
		},
		"Urban Areas Summary Report": {
			"Geo ID": "Identification number associated with the geographic area",
			"Name": "Name of the geographic area",
			"Population (2010)": "Total population of the geographic area",
			"Land Area (in sq. mi.)": "Total land area of the geographic area",
			"Water Area (in sq. mi.)": "Total water area of the geographic area",
			"Routes Count": "Count of routes within the given geographic area",
			"Stops Count": "Count of stops within the given geographic area",			
		},
		"Urban Areas Extended Report": {
			"Geo ID": "Identification number associated with the geographic area",
			"Name": "Name of the geographic area",
			"Fare": "The fare information published in the transit agency's GTFS feed",
			"Route Miles": "Summation of the lengths of the longest trips within the given geographic area",			
			"Service Hours": "This is the total hours a transit agency spends on serving all round trips within the given geographic area. Service Hours may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Miles": "This is the total miles driven over all round trips within the given geographic area. Service Miles may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Miles Per Square Mile": "Service Miles divided by the area of the given geographic area",
			"Stops Per Square Mile": "Stops Count divided by the area of given geographic area",
			"Stops Per Service Mile": "Stops Count in the given geographic area divided by Service Miles",
			"Miles of Service Per Capita": "Service Miles divided by the population of the geographic area",
			"Population Served (Unduplicated)": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area",
			"Percent of Population Served": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area divided by total population of the given geographic area",
			"Percent of Population Served at Level of Service": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area that receives a specified minimum level of service divided by total population of the given geographic area",
			"Percent Population Unserved": "One hundred percent minus Percent of Population Served",
			"Service Stops": "This is Stops Count within the given geographic area multiplied by the number of times each stop is being served for the given date(s). The reported numbers are cumulative over the selected dates.",
			"Population Served By Service": "Population Served by Service is calculated as Service Stops multiplied by the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area for every trip. The reported numbers are cumulative over the selected dates.",
			"Service Days": "Set of days (from the selected days) in which at least one trip within the given geographic area is served",
			"Connected Communities": "List of geographic areas of the same type that are connected to the given geographic area through routes",
			"Hours of Service": "Earliest arrival and latest departure times of all stops within the given geographic area",
			"Average Fare": "Fare average for the given geographic area",
			"Median Fare": "Fare median for the given geographic area",
		},
		"Congressional Districts Summary Report": {
			"Geo ID": "Identification number associated with the geographic area",
			"Name": "Name of the geographic area",
			"Population (2010)": "Total population of the geographic area",
			"Land Area (in sq. mi.)": "Total land area of the geographic area",
			"Water Area (in sq. mi.)": "Total water area of the geographic area",
			"Routes Count": "Count of routes within the given geographic area",
			"Urban Stops Count": "Count of urban stops within the given geographic area",
			"Rural Stops Count": "Count of rural stops within the given geographic area",
			"Urbanized Areas" :"Total number of Urbanized Areas within the geographic area",
			"Urban Clusters" :"Total number of Urban Clusters within the geographic area",
			
		},
		"Congressional Districts Extended Report": {
			"Geo ID": "Identification number associated with the geographic area",
			"Name": "Name of the geographic area",
			"Fare": "The fare information published in the transit agency's GTFS feed",
			"Route Miles": "Summation of the lengths of the longest trips within the given geographic area",			
			"Service Hours": "This is the total hours a transit agency spends on serving all round trips within the given geographic area. Service Hours may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Miles": "This is the total miles driven over all round trips within the given geographic area. Service Miles may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Miles Per Square Mile": "Service Miles divided by the area of the given geographic area",
			"Stops Per Square Mile": "Stops Count divided by the area of given geographic area",
			"Stops Per Service Mile": "Stops Count in the given geographic area divided by Service Miles",
			"Miles of Service Per Capita": "Service Miles divided by the population of the geographic area",
			"Population Served (Unduplicated)": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area",
			"Percent of Population Served": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area divided by total population of the given geographic area",
			"Percent of Population Served at Level of Service": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area that receives a specified minimum level of service divided by total population of the given geographic area",
			"Percent Population Unserved": "One hundred percent minus Percent of Population Served",
			"Urban Service Stops": "This is the Urban Stops Count within the given geographic area multiplied by the number of times each stop is being served for the given date(s). The reported numbers are cumulative over the selected dates.",
			"Rural Service Stops": "This is the Rural Stops Count within the given geographic area multiplied by the number of times each stop is being served for the given date(s). The reported numbers are cumulative over the selected dates.",
			"Population Served By Service": "Population Served by Service is calculated as Service Stops multiplied by the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area for every trip. The reported numbers are cumulative over the selected dates.",
			"Service Days": "Set of days (from the selected days) in which at least one trip within the given geographic area is served",
			"Connected Communities": "List of geographic areas of the same type that are connected to the given geographic area through routes",
			"Hours of Service": "Earliest arrival and latest departure times of all stops within the given geographic area",
			"Average Fare": "Fare average for the given geographic area",
			"Median Fare": "Fare median for the given geographic area",			
		},
		"ODOT Transit Regions Summary Report": {
			"Geo ID": "Identification number associated with the geographic area",
			"Name": "Name of the geographic area",
			"Population (2010)": "Total population of the geographic area",
			"Land Area (in sq. mi.)": "Total land area of the geographic area",
			"Water Area (in sq. mi.)": "Total water area of the geographic area",
			"Routes Count": "Count of routes within the given geographic area",
			"Urban Stops Count": "Count of urban stops within the given geographic area",
			"Rural Stops Count": "Count of rural stops within the given geographic area",
			"Urbanized Areas" :"Total number of Urbanized Areas within the geographic area",
			"Urban Clusters" :"Total number of Urban Clusters within the geographic area",
			"Counties Count": "Count of counties within the geographic area",
		},
		"ODOT Transit Regions Extended Report": {
			"Geo ID": "Identification number associated with the geographic area",
			"Name": "Name of the geographic area",
			"Fare": "The fare information published in the transit agency's GTFS feed",
			"Route Miles": "Summation of the lengths of the longest trips within the given geographic area",			
			"Service Hours": "This is the total hours a transit agency spends on serving all round trips within the given geographic area. Service Hours may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Miles": "This is the total miles driven over all round trips within the given geographic area. Service Miles may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Miles Per Square Mile": "Service Miles divided by the area of the given geographic area",
			"Stops Per Square Mile": "Stops Count divided by the area of given geographic area",
			"Stops Per Service Mile": "Stops Count in the given geographic area divided by Service Miles",
			"Miles of Service Per Capita": "Service Miles divided by the population of the geographic area",
			"Population Served (Unduplicated)": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area",
			"Percent of Population Served": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area divided by total population of the given geographic area",
			"Percent of Population Served at Level of Service": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area that receives a specified minimum level of service divided by total population of the given geographic area",
			"Percent Population Unserved": "One hundred percent minus Percent of Population Served",
			"Urban Service Stops": "This is the Urban Stops Count within the given geographic area multiplied by the number of times each stop is being served for the given date(s). The reported numbers are cumulative over the selected dates.",
			"Rural Service Stops": "This is the Rural Stops Count within the given geographic area multiplied by the number of times each stop is being served for the given date(s). The reported numbers are cumulative over the selected dates.",
			"Population Served By Service": "Population Served by Service is calculated as Service Stops multiplied by the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area for every trip. The reported numbers are cumulative over the selected dates.",
			"Service Days": "Set of days (from the selected days) in which at least one trip within the given geographic area is served",
			"Connected Communities": "List of geographic areas of the same type that are connected to the given geographic area through routes",
			"Hours of Service": "Earliest arrival and latest departure times of all stops within the given geographic area",
			"Average Fare": "Fare average for the given geographic area",
			"Median Fare": "Fare median for the given geographic area",
		},
		"Census Places Summary Report": {
			"Geo ID": "Identification number associated with the geographic area",
			"Name": "Name of the geographic area",
			"Population (2010)": "Total population of the geographic area",
			"Land Area (in sq. mi.)": "Total land area of the geographic area",
			"Water Area (in sq. mi.)": "Total water area of the geographic area",
			"Routes Count": "Count of routes within the given geographic area",
			"Urban Stops Count": "Count of urban stops within the given geographic area",
			"Rural Stops Count": "Count of rural stops within the given geographic area",
			"Urbanized Areas" :"Total number of Urbanized Areas within the geographic area",
			"Urban Clusters" :"Total number of Urban Clusters within the geographic area",
			
		},
		"Census Places Extended Report": {
			"Geo ID": "Identification number associated with the geographic area",
			"Name": "Name of the geographic area",
			"Fare": "The fare information published in the transit agency's GTFS feed",
			"Route Miles": "Summation of the lengths of the longest trips within the given geographic area",			
			"Service Hours": "This is the total hours a transit agency spends on serving all round trips within the given geographic area. Service Hours may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Miles": "This is the total miles driven over all round trips within the given geographic area. Service Miles may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Miles Per Square Mile": "Service Miles divided by the area of the given geographic area",
			"Stops Per Square Mile": "Stops Count divided by the area of given geographic area",
			"Stops Per Service Mile": "Stops Count in the given geographic area divided by Service Miles",
			"Miles of Service Per Capita": "Service Miles divided by the population of the geographic area",
			"Population Served (Unduplicated)": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area",
			"Percent of Population Served": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area divided by total population of the given geographic area",
			"Percent of Population Served at Level of Service": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area that receives a specified minimum level of service divided by total population of the given geographic area",
			"Percent Population Unserved": "One hundred percent minus Percent of Population Served",
			"Urban Service Stops": "This is the Urban Stops Count within the given geographic area multiplied by the number of times each stop is being served for the given date(s). The reported numbers are cumulative over the selected dates.",
			"Rural Service Stops": "This is the Rural Stops Count within the given geographic area multiplied by the number of times each stop is being served for the given date(s). The reported numbers are cumulative over the selected dates.",
			"Population Served By Service": "Population Served by Service is calculated as Service Stops multiplied by the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area for every trip. The reported numbers are cumulative over the selected dates.",
			"Service Days": "Set of days (from the selected days) in which at least one trip within the given geographic area is served",
			"Connected Communities": "List of geographic areas of the same type that are connected to the given geographic area through routes",
			"Hours of Service": "Earliest arrival and latest departure times of all stops within the given geographic area",
			"Average Fare": "Fare average for the given geographic area",
			"Median Fare": "Fare median for the given geographic area",
		},
		"Census Tracts Summary Report": {
			"Geo ID": "Identification number associated with the geographic area",
			"Name": "Name of the geographic area",
			"Population (2010)": "Total population of the geographic area",
			"Land Area (in sq. mi.)": "Total land area of the geographic area",
			"Water Area (in sq. mi.)": "Total water area of the geographic area",
			"Routes Count": "Count of routes within the given geographic area",
			"Urban Stops Count": "Count of urban stops within the given geographic area",
			"Rural Stops Count": "Count of rural stops within the given geographic area",
			"Urbanized Areas" :"Total number of Urbanized Areas within the geographic area",
			"Urban Clusters" :"Total number of Urban Clusters within the geographic area",
			
		},
		"Census Tracts Extended Report": {
			"Geo ID": "Identification number associated with the geographic area",
			"Name": "Name of the geographic area",
			"Fare": "The fare information published in the transit agency's GTFS feed",
			"Route Miles": "Summation of the lengths of the longest trips within the given geographic area",			
			"Service Hours": "This is the total hours a transit agency spends on serving all round trips within the given geographic area. Service Hours may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Miles": "This is the total miles driven over all round trips within the given geographic area. Service Miles may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Miles Per Square Mile": "Service Miles divided by the area of the given geographic area",
			"Stops Per Square Mile": "Stops Count divided by the area of given geographic area",
			"Stops Per Service Mile": "Stops Count in the given geographic area divided by Service Miles",
			"Miles of Service Per Capita": "Service Miles divided by the population of the geographic area",
			"Population Served (Unduplicated)": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area",
			"Percent of Population Served": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area divided by total population of the given geographic area",
			"Percent of Population Served at Level of Service": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area that receives a specified minimum level of service divided by total population of the given geographic area",
			"Percent Population Unserved": "One hundred percent minus Percent of Population Served",
			"Urban Service Stops": "This is the Urban Stops Count within the given geographic area multiplied by the number of times each stop is being served for the given date(s). The reported numbers are cumulative over the selected dates.",
			"Rural Service Stops": "This is the Rural Stops Count within the given geographic area multiplied by the number of times each stop is being served for the given date(s). The reported numbers are cumulative over the selected dates.",
			"Population Served By Service": "Population Served by Service is calculated as Service Stops multiplied by the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area for every trip. The reported numbers are cumulative over the selected dates.",
			"Service Days": "Set of days (from the selected days) in which at least one trip within the given geographic area is served",
			"Connected Communities": "List of geographic areas of the same type that are connected to the given geographic area through routes",
			"Hours of Service": "Earliest arrival and latest departure times of all stops within the given geographic area",
			"Average Fare": "Fare average for the given geographic area",
			"Median Fare": "Fare median for the given geographic area",
		},
		"Counties Summary Report": {
			"Geo ID": "Identification number associated with the geographic area",
			"Name": "Name of the geographic area",
			"ODOT Region ID": "ODOT transit region identification number associated with the geographic area",
			"ODOT Transit Region": "ODOT transit region name associated with the geographic area",
			"Population (2010)": "Total population of the geographic area",
			"Land Area (in sq. mi.)": "Total land area of the geographic area",
			"Water Area (in sq. mi.)": "Total water area of the geographic area",
			"Routes Count": "Count of routes within the given geographic area",
			"Urban Stops Count": "Count of urban stops within the given geographic area",
			"Rural Stops Count": "Count of rural stops within the given geographic area",
			"Urbanized Areas" :"Total number of Urbanized Areas within the geographic area",
			"Urban Clusters" :"Total number of Urban Clusters within the geographic area",	
			"Tracts Count": "Count of census tracts within the given geographic area",
		},
		"Counties Extended Report": {
			"Geo ID": "Identification number associated with the geographic area",
			"Name": "Name of the geographic area",
			"Fare": "The fare information published in the transit agency's GTFS feed",
			"Route Miles": "Summation of the lengths of the longest trips within the given geographic area",			
			"Service Hours": "This is the total hours a transit agency spends on serving all round trips within the given geographic area. Service Hours may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Miles": "This is the total miles driven over all round trips within the given geographic area. Service Miles may be calculated for a specific date or a set of specified dates using the calendar. The reported numbers are cumulative over the selected dates.",
			"Service Miles Per Square Mile": "Service Miles divided by the area of the given geographic area",
			"Stops Per Square Mile": "Stops Count divided by the area of given geographic area",
			"Stops Per Service Mile": "Stops Count in the given geographic area divided by Service Miles",
			"Miles of Service Per Capita": "Service Miles divided by the population of the geographic area",
			"Population Served (Unduplicated)": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area",
			"Percent of Population Served": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area divided by total population of the given geographic area",
			"Percent of Population Served at Level of Service": "Summation of the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area that receives a specified minimum level of service divided by total population of the given geographic area",
			"Percent Population Unserved": "One hundred percent minus Percent of Population Served",
			"Urban Service Stops": "This is the Urban Stops Count within the given geographic area multiplied by the number of times each stop is being served for the given date(s). The reported numbers are cumulative over the selected dates.",
			"Rural Service Stops": "This is the Rural Stops Count within the given geographic area multiplied by the number of times each stop is being served for the given date(s). The reported numbers are cumulative over the selected dates.",
			"Population Served By Service": "Population Served by Service is calculated as Service Stops multiplied by the unduplicated population within an X-mile radius (i.e., stop distance) of all stops within the given geographic area for every trip. The reported numbers are cumulative over the selected dates.",
			"Service Days": "Set of days (from the selected days) in which at least one trip within the given geographic area is served",
			"Connected Communities": "List of geographic areas of the same type that are connected to the given geographic area through routes",
			"Hours of Service": "Earliest arrival and latest departure times of all stops within the given geographic area",
			"Average Fare": "Fare average for the given geographic area",
			"Median Fare": "Fare median for the given geographic area",
		},
		"Multimodal Hub Summary Report": {
			"ID": "This is the identification number assigned to the cluster based on its importance. A lower ID means a higher cluster importance.",
			"Transit Agencies": "Unduplicated list of transit agencies that serve stops in the cluster",
			"Routes": "Unduplicated list of routes that serve stops in the cluster",
			"Stops": "Detailed list of stops in the cluster",
			"Agency Count": "Count of transit agencies that serve stops in the cluster",
			"Route Count": "Count of routes that serve stops in the cluster",
			"Visit Count": "Count of times all stops in the cluster are served",
			"Stops Count": "Count of stops in the cluster",
		},
		"Connected Agencies Summary Report": {
			"Agency ID": "Identification number reported in the transit agency's GTFS feed",
			"Name": "Agency name reported in the transit agency's GTFS feed",
			"Number of Connected Agencies": "Number of transit agencies that have at least one stop within the specified distance of the selected transit agency's stops",
			"Connected Agency ID": "Agency IDs corresponding with transit agencies that have at least one stop within the specified distance of the selected transit agency's stops",
			"Connected Agency Details": "Name of transit agencies that have at least one stop within the specified distance of the selected transit agency's stops and minimum spatial gap (in feet) between the transit agencies listed and the selected transit agency",
			"Connected Agency Names": "Name of transit agencies that have at least one stop within the specified distance of the selected transit agency's stops",
			"Connected Agency Min. Spatial Gap (in ft.)": "Minimum spatial gap between between the transit agencies listed and the selected transit agency",
		},
		"Connected Agencies Extended Report": {
			"Agency ID": "Identification number reported in the transit agency's GTFS feed",
			"Name": "Agency name reported in the transit agency's GTFS feed",
			"Number of Connections": "Number of transit agencies that have at least one stop within the specified distance of the selected transit agency's stops",
			"Min Connection distance (in ft.)": "Smallest distance between the stops of the listed transit agency and the selected transit agency's stops",
			"Max Connection distance (in ft.)": "Largest distance between the stops of the listed transit agency and the selected transit agency's stops",
			"Average Connection distance (in ft.)": "Average distance between the stops of the listed transit agency and the selected transit agency's stops",
			"Connections": "List of stops within the specified distance of the selected transit agency's stops and the distance (in feet) between them",
		}
	};  
