version: "3"

volumes:
  pgdata:
  conf:

services:
  nginx:
    restart: always
    image: nginx:alpine
    volumes:
     - ./nginx/tnext.conf:/etc/nginx/conf.d/tnext.conf
    ports:
      - "8080:8080"
    links:
      - tnext      

  db:
    restart: always
    command: postgres --log_statement=all
    image: mdillon/postgis:9.6
    env_file: ENVIRONMENT_VARS.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"

  tnext:
    build: .
    restart: always
    env_file: ENVIRONMENT_VARS.env
    volumes:
      - ./data:/data
      - ./conf:/app/conf
    ports:
      - "8080"
    links:
      - db
