#!/bin/bash
set -ex

ENDPOINT="http://localhost:8080/TNAtoolAPI-Webapp"
OLDDB="0,september17,,,jdbc:postgresql://db:5432/september17,postgres,postgres,,,"
NEWDB="1,test18,,,jdbc:postgresql://db:5432/test18,postgres,postgres,,,"

# add
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkForDeactivated?&db=${OLDDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/getIndex"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkInput?&dbname=test18&cURL=jdbc:postgresql://db:5432/&user=postgres&pass=postgres&db=test18&oldURL=&olddbname="    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/addDB?&db=${NEWDB}"    

# clear
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/readDBinfo"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${OLDDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/deleteUploadedGTFS"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/deleteUploadedPNR"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/deleteUploadedT6"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/deleteUploadedEmp"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/deleteUploadedfEmp"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/deleteUploadedfPop"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/deleteUploadedRegion"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDuplicateFeeds?&db=${NEWDB}&feed=531.zip"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDuplicateFeeds?&db=${NEWDB}&feed=456.zip"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/deleteProcessGTFS"    

# feeds

# curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/addfeed?&feedname=columbia-area-transit-operated-by-hood-river-county-transportation-district.zip&feedsize=175359&db=${NEWDB}"    
curl -s --fail -u admin:tnast -X POST  "${ENDPOINT}/admin" -F "files[]=@531.zip" -F "name=gtfs"
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/addfeed?&feedname=531.zip&feedsize=0&db=${NEWDB}"

# curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/addfeed?&feedname=albany-transit-system.zip&feedsize=105555&db=${NEWDB}"    
curl -s --fail -u admin:tnast -X POST  "${ENDPOINT}/admin" -F "files[]=@456.zip" -F "name=gtfs"
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/addfeed?&feedname=456.zip&feedsize=0&db=${NEWDB}"

# 
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkGTFSstatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/changeDBStatus?&db=${NEWDB}&field=gtfs_feeds&b=true"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${OLDDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkUpdatestatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/deleteUploadedGTFS"    

# census
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/copyCensus?&dbFrom=${OLDDB}&dbTo=${NEWDB}&section=census"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkCensusstatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/changeDBStatus?&db=${NEWDB}&field=census&b=true"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${OLDDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkUpdatestatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/getImportedStates?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkFpopstatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/changeDBStatus?&db=${NEWDB}&field=future_pop&b=true"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${OLDDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/getImportedStates?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkRegionstatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/changeDBStatus?&db=${NEWDB}&field=region&b=true"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${OLDDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/getImportedStates?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkfEmpstatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/getImportedStates?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkEmpstatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/getImportedStates?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkT6status?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/getImportedStates?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkPNRstatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/copyCensus?&dbFrom=${OLDDB}&dbTo=${NEWDB}&section=employment"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/getImportedStates?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkEmpstatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/changeDBStatus?&db=${NEWDB}&field=employment&b=true"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${OLDDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/copyCensus?&dbFrom=${OLDDB}&dbTo=${NEWDB}&section=parknride"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/getImportedStates?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkPNRstatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/changeDBStatus?&db=${NEWDB}&field=parknride&b=true"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${OLDDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/copyCensus?&dbFrom=${OLDDB}&dbTo=${NEWDB}&section=title6"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/getImportedStates?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkT6status?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/changeDBStatus?&db=${NEWDB}&field=title6&b=true"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${OLDDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/copyCensus?&dbFrom=${OLDDB}&dbTo=${NEWDB}&section=femployment"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/getImportedStates?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkfEmpstatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/changeDBStatus?&db=${NEWDB}&field=future_emp&b=true"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${OLDDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${NEWDB}"    

# update queries
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/updateFeeds?&db=${NEWDB}&username=admin"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/updateNext?&feed=531&db=${NEWDB}&agency=531&username=admin"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/updateNext?&feed=531&db=${NEWDB}&agency=37&username=admin"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/updateNext?&feed=456&db=${NEWDB}&agency=456&username=admin"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/updateNext?&feed=456&db=${NEWDB}&agency=457&username=admin"    

# activate
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkUpdatestatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/changeDBStatus?&db=${NEWDB}&field=update_process&b=true"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${OLDDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/checkDBStatus?&db=${NEWDB}"    
curl -s --fail -u admin:tnast "${ENDPOINT}/modifiers/dbupdate/activateDBs?&db=${NEWDB}"  